spring.application.name=backend

spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

gemini.api.key=${GEMINI_API_KEY}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

admin.emails=${ADMIN_EMAILS:anshika1179@gmail.com}
admin.password=${ADMIN_PASSWORD:admin123}

spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH_JWK_SET_URI}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH_ISSUER_URI}

