spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-little-hat-adksx7ej-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RIafTpP83OUS

spring.datasource.driver-class-name=org.postgresql.Driver
